import { FlashcardStudio } from "@/components/flashcard-studio"
import { PageHeader } from "@/components/page-header"
import { createClient } from "@/lib/supabase/server"
import type { Flashcard } from "@/lib/database.types"

export const dynamic = "force-dynamic"

/**
 * Flashcards — persistent spaced-repetition decks.
 * Cards are generated by the agent, saved per user, and resurface on an
 * SM-2 style schedule so revision happens right before forgetting.
 */
export default async function FlashcardsPage({
  searchParams,
}: {
  searchParams: Promise<{ topic?: string }>
}) {
  const supabase = await createClient()
  const params = await searchParams

  let cards: Flashcard[] = []
  if (supabase) {
    const { data } = await supabase
      .from("flashcards")
      .select("*")
      .order("due_at", { ascending: true })
      .limit(500)
    cards = data ?? []
  }

  return (
    <main className="flex flex-col gap-6">
      <PageHeader
        title="Flashcards"
        subtitle="Spaced repetition — review cards right before you forget them."
      />

      <FlashcardStudio initialCards={cards} initialTopic={params.topic ?? ""} />
    </main>
  )
}
